<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentAssertions" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="NetArchTest.Rules" />
        <PackageReference Include="xunit.v3" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\scr\EventForge.Booking.Application\EventForge.Booking.Application.csproj" />
        <ProjectReference Include="..\..\scr\EventForge.Booking.Domain\EventForge.Booking.Domain.csproj" />
        <ProjectReference Include="..\..\scr\EventForge.Booking.Infrastructure\EventForge.Booking.Infrastructure.csproj" />
        <ProjectReference Include="..\..\scr\EventForge.Booking.Presentation\EventForge.Booking.Presentation.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

</Project>
