<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentAssertions" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="NetArchTest.Rules" />
        <PackageReference Include="xunit.v3" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\scr\EventForge.Events.Application\EventForge.Events.Application.csproj" />
        <ProjectReference Include="..\..\scr\EventForge.Events.Domain\EventForge.Events.Domain.csproj" />
        <ProjectReference Include="..\..\scr\EventForge.Events.Infrastructure\EventForge.Events.Infrastructure.csproj" />
        <ProjectReference Include="..\..\scr\EventForge.Events.Presentation\EventForge.Events.Presentation.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

</Project>
